name: pooled-cp
channels:
- conda-forge
dependencies:
- conda-forge::python=3.7.1
- conda-forge::pandas=1.0.1
- conda-forge::numpy=1.18.4
- conda-forge::scipy=1.4.1
- conda-forge::pathlib=1.0.1
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=5.1.0
- conda-forge::nb_conda_kernels=2.2.1
- conda-forge::widgetsnbextension=3.5.1
- conda-forge::jupyter_contrib_nbextensions=0.5.1
- conda-forge::matplotlib=3.1.3
- conda-forge::plotnine=0.6.0
- conda-forge::seaborn=0.10.1
- conda-forge::black=19.10b0
- conda-forge::nb_black=1.0.7
